[toolchain]
# <<<<<<< HEAD
# # channel = "nightly"
# # stable-aarch64-unknown-linux-gnu
# targets= ["aarch64-unknown-linux-gnu"]
#
# =======
channel = "nightly"
#stable-aarch64-unknown-linux-gnu
# >>>>>>> wip problems with toolchain
