[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"
# [build]
# target = "wasm32-unknown-unknown"
[alias]     # command aliases
b = "build"
c = "check"
t = "test"
r = "run"
rr = "run --release"
[env]
# CRON_STRING = "0 0 5 1/2 * * *"
# CRON_STRING = "0 24 20 * * * *"
CRON_STRING = "1 4,17 * * * * *"
SECONDS_TO_PUMP_WATER = {value= "20"}
