pub mod activate_pin_component;
pub mod cancel_pump_component;
pub mod canvas_component;
pub mod change_cron_string_component;
pub mod change_seconds_to_pump_water_component;
pub mod pump_help_component;
pub mod pump_water_check_component;
pub mod pump_water_copmpnent;
pub mod set_and_display_generic_component;
