name: test

on: [push,pull_request]


env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: cargo leptos test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2
    - name: say hello
      run: echo "hello world from yarin"
    - name: install cargo leptos@v0.1.7
      run: cargo install cargo-leptos
    - name: Run tests
      run: cargo leptos test


